name: Issue Comment

on:
  issues:
    types: [opened]

jobs:
  issue-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Comment on new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./issue-comment.js');
            script({github, context});
