name: Workflow Commands
on: [push]
defaults:
  run:
    shell: bash
    working-directory: /home/runner/work
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: List Files
        working-directory: /home/runner/work/gh-update-tests
        run: |
          Get-Location 
          dir
          Write-Output $env:GITHUB_SHA
          Write-Output $env:GITHUB_REPOSITORY
          Write-Output $env:GITHUB_WORKSPACE
      - name: Python shell
        shell: python
        run: |
          import platform 
          print(platform.processor())
